// Code generated by MockGen. DO NOT EDIT.
// Source: internal/provider/provider.go
//
// Generated by this command:
//
//	mockgen -source=internal/provider/provider.go -destination=internal/provider/mockprovider/mock_provider.go -package=mockprovider
//

// Package mockprovider is a generated GoMock package.
package mockprovider

import (
	context "context"
	http "net/http"
	reflect "reflect"

	types "github.com/warm3snow/llm-gateway/internal/types"
	gomock "go.uber.org/mock/gomock"
)

// MockProvider is a mock of Provider interface.
type MockProvider struct {
	ctrl     *gomock.Controller
	recorder *MockProviderMockRecorder
	isgomock struct{}
}

// MockProviderMockRecorder is the mock recorder for MockProvider.
type MockProviderMockRecorder struct {
	mock *MockProvider
}

// NewMockProvider creates a new mock instance.
func NewMockProvider(ctrl *gomock.Controller) *MockProvider {
	mock := &MockProvider{ctrl: ctrl}
	mock.recorder = &MockProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProvider) EXPECT() *MockProviderMockRecorder {
	return m.recorder
}

// AudioSpeech mocks base method.
func (m *MockProvider) AudioSpeech(ctx context.Context, req map[string]any, opts *types.Options) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AudioSpeech", ctx, req, opts)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AudioSpeech indicates an expected call of AudioSpeech.
func (mr *MockProviderMockRecorder) AudioSpeech(ctx, req, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AudioSpeech", reflect.TypeOf((*MockProvider)(nil).AudioSpeech), ctx, req, opts)
}

// AudioTranscription mocks base method.
func (m *MockProvider) AudioTranscription(ctx context.Context, req map[string]any, opts *types.Options) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AudioTranscription", ctx, req, opts)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AudioTranscription indicates an expected call of AudioTranscription.
func (mr *MockProviderMockRecorder) AudioTranscription(ctx, req, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AudioTranscription", reflect.TypeOf((*MockProvider)(nil).AudioTranscription), ctx, req, opts)
}

// ChatCompletion mocks base method.
func (m *MockProvider) ChatCompletion(ctx context.Context, req *types.ChatCompletionRequest, opts *types.Options) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChatCompletion", ctx, req, opts)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChatCompletion indicates an expected call of ChatCompletion.
func (mr *MockProviderMockRecorder) ChatCompletion(ctx, req, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChatCompletion", reflect.TypeOf((*MockProvider)(nil).ChatCompletion), ctx, req, opts)
}

// Completion mocks base method.
func (m *MockProvider) Completion(ctx context.Context, req *types.CompletionRequest, opts *types.Options) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Completion", ctx, req, opts)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Completion indicates an expected call of Completion.
func (mr *MockProviderMockRecorder) Completion(ctx, req, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Completion", reflect.TypeOf((*MockProvider)(nil).Completion), ctx, req, opts)
}

// Embedding mocks base method.
func (m *MockProvider) Embedding(ctx context.Context, req *types.EmbeddingRequest, opts *types.Options) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Embedding", ctx, req, opts)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Embedding indicates an expected call of Embedding.
func (mr *MockProviderMockRecorder) Embedding(ctx, req, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Embedding", reflect.TypeOf((*MockProvider)(nil).Embedding), ctx, req, opts)
}

// GetBaseURL mocks base method.
func (m *MockProvider) GetBaseURL() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBaseURL")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetBaseURL indicates an expected call of GetBaseURL.
func (mr *MockProviderMockRecorder) GetBaseURL() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBaseURL", reflect.TypeOf((*MockProvider)(nil).GetBaseURL))
}

// GetEndpoints mocks base method.
func (m *MockProvider) GetEndpoints() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEndpoints")
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetEndpoints indicates an expected call of GetEndpoints.
func (mr *MockProviderMockRecorder) GetEndpoints() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEndpoints", reflect.TypeOf((*MockProvider)(nil).GetEndpoints))
}

// GetName mocks base method.
func (m *MockProvider) GetName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetName indicates an expected call of GetName.
func (mr *MockProviderMockRecorder) GetName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetName", reflect.TypeOf((*MockProvider)(nil).GetName))
}

// ImageGeneration mocks base method.
func (m *MockProvider) ImageGeneration(ctx context.Context, req map[string]any, opts *types.Options) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImageGeneration", ctx, req, opts)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ImageGeneration indicates an expected call of ImageGeneration.
func (mr *MockProviderMockRecorder) ImageGeneration(ctx, req, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImageGeneration", reflect.TypeOf((*MockProvider)(nil).ImageGeneration), ctx, req, opts)
}

// Models mocks base method.
func (m *MockProvider) Models(ctx context.Context, opts *types.Options) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Models", ctx, opts)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Models indicates an expected call of Models.
func (mr *MockProviderMockRecorder) Models(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Models", reflect.TypeOf((*MockProvider)(nil).Models), ctx, opts)
}

// TransformRequest mocks base method.
func (m *MockProvider) TransformRequest(endpoint string, req any) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransformRequest", endpoint, req)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TransformRequest indicates an expected call of TransformRequest.
func (mr *MockProviderMockRecorder) TransformRequest(endpoint, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransformRequest", reflect.TypeOf((*MockProvider)(nil).TransformRequest), endpoint, req)
}

// TransformResponse mocks base method.
func (m *MockProvider) TransformResponse(endpoint string, resp *http.Response) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransformResponse", endpoint, resp)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TransformResponse indicates an expected call of TransformResponse.
func (mr *MockProviderMockRecorder) TransformResponse(endpoint, resp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransformResponse", reflect.TypeOf((*MockProvider)(nil).TransformResponse), endpoint, resp)
}
